spring.application.name=rateLimiter
rate.limiter.token-bucket.window-in-seconds=60

rate.limiter.token-bucket.max-requests=10

rate.limiter.fixed-window.window-in-seconds=60

rate.limiter.fixed-window.max-requests=5

rate.limiter.sliding-window.window-in-seconds=60

rate.limiter.sliding-window.max-requests=5